config/routes.rb
Rails.application.routes.draw do

root 'pages#home'
  
    get 'pages/about' => 'pages#about'
    get 'signup' => 'users#new'
   
       get 'login' => 'sessions#new'
       post 'login' => 'sessions#create'
       delete 'logout' => 'sessions#destroy'
 
	resources :articles
	resources :users, except: [:new]
	

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	
	validates :title, presence: true, length: {minimum: 3, maximum: 20}
	validates :description, presence: true, length: {minimum: 3, maximum: 50}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
	has_secure_password
	before_save {self.email = email.downcase}
	
	validates :username, 
			presence: true, uniqueness: {case_sensitive: false},
			length: {minimum: 3, maximum: 25}
	
	VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]{1,50}\.[a-z]{2,10}\z/i
	
	validates :email,
			presence: true, uniqueness: {case_sensitive: false},
			length: {minimum: 3, maximum: 50},
			format: {with: VALID_EMAIL_REGEX}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
  	!!current_user
  end
  
  def require_user
	if !logged_in?
		flash[:danger] = "You must be logged in to perform that function!"
		redirect_to root_path
	end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :find_article, only: [:edit, :update, :destroy, :show]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	
	def index
		@articles = Article.paginate(page: params[:page], per_page: 3)
	end
	
	def new
		@article= Article.new
	end
	
	def edit 

	end
	
	def show

	end
	
	def create
		debugger
		# render plain: params[:article].inspect
		@article = Article.new(article_params)
		@article.user = User.first
		
		if	(@article.save)
			flash[:success] = "Article was successfully created."
			redirect_to article_path(@article)
		else
			# flash[:notice] = "Could not create article."
			render :new
		end
	end
	
	def update
		# render plain: params[:article].inspect
		
		if	(@article.update(article_params))
			flash[:success] = "Article was successfully updated."
			redirect_to article_path(@article)
		else
			# flash[:notice] = "Could not create article."
			render :edit
		end
	end
	
	def destroy
			@article.destroy
			flash[:danger] = "Article was successfully removed."
			redirect_to articles_path
	end
	
	private
		def find_article
				@article = Article.find(params[:id])
		end
	
		def article_params # whitelist the parameters
			params.require(:article).permit(:title, :description)
		end
		
		def require_same_user
			if current_user != @article.user
				flash[:danger] = "Silly wabbit!  You can't make changes to someone else's article!"
				redirect_to root_path
			end
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    	redirect_to articles_path if logged_in?
    end
    
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	
	end
	
	def create
		user = User.find_by(email: params[:session][:email].downcase)
	   if (user && user.authenticate(params[:session][:password]))
			session[:user_id] = user.id
			flash[:success]="You have successfully logged in!"
			redirect_to user_path(user)
		else
			flash.now[:danger]="Your username or password is incorrect."
			render 'new'
		end
	end
	
	def destroy
		session[:user_id] = nil
		flash[:success] = "You have successfully logged out"
		redirect_to root_path
	
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	
	def index
		@users = User.paginate(page: params[:page], per_page: 3)
	end
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		
		if(@user.save)
			flash[:success] = "Welcome to KW's Alpha Blog #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end
	end
	
	def edit

	end
	
	def update
		if(@user.update(user_params))
			flash[:success] = "Your account has been updated successfully"
			redirect_to articles_path
		else
			render 'edit'
		end
	end
	
	def show
			@user_articles = @user.articles.paginate(page: params[:page], per_page: 2)
	end
	
	def set_user
		  @user = User.find(params[:id])
	end

private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options= {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/articles/_article.html.erb
<% objs.each do |article| %>
	<div class="row text-left">
		<div class="col-xs-8" "col-xs-offset-2">
			<div class="well well-lg">
			
				<div class="article-title">
					<%= link_to article.title, article_path(article) %>
				</div>	
				
				<div class="article-body">
					<%=  truncate(article.description, length: 100) %>
					
					<div class="article-meta-details">
							<small>
									Created By: "<%= article.user.username if article.user %>",
									Created <%= time_ago_in_words(article.created_at) %> ago,
									Last Updated: <%= time_ago_in_words(article.updated_at) %> ago				
							</small>
					</div>
				</div>

				<%= render "articles/articleactions", obj: article, article_user:article.user %>		


			</div>		
		</div>	
	</div>
<% end %>

<!--<p>
	<%= link_to "Create new article", new_article_path %>
</p>

<table summary="All articles can be seen below">
<tr>
	<th>Title</th>
	<th>Description</th>
	<th>Edit Article</th>
	<th>Show Article</th>
	<th>Destroy Article</th>
</tr>

<% objs.each do |article| %>
<tr>
	<td><%= article.title %></td>
	<td><%=  article.description %></td>
	<td>	<%= link_to "Edit article", edit_article_path(article) %></td>
	<td><%= link_to "Show article", article_path(article) %></td>
	<td><%= link_to "Remove article", article_path(article), method: :delete, data: {confirm: "Confirm article deletion (can't be undone)!"} %></td>
</tr>
<% end %>

</table>
-->
<%= render "shared/footer" %>

app/views/articles/_articleactions.html.erb
<div class="article-actions">
<% if logged_in? && current_user == article_user %>
	<%= link_to "Edit current article", edit_article_path(obj), class: "btn btn-xs btn-primary" %> |
	<%= link_to "Destroy Current Article", article_path(obj), method: :delete, data: {confirm: "Confirm you want to delete this article."}, class: "btn btn-xs btn-danger" %> | 
<% end %>
	<%= link_to "View All Articles", articles_path, class: "btn btn-xs btn-primary" %> 

</div>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>
	
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@article, :html=>{class:"form-horizontal", role:"form"}) do |f| %>
		<div class="form-group">
    		<div class="col-sm-2 control-label">
    			<%= f.label :title %>
    		</div>
    		
    		<div class="col-sm-6">
      			<%= f.text_field :title, class: "form-control", placeholder: "Article Title", autofocus: true  %>
    		</div>
  		</div>
  
   		<div class="form-group">
    		<div class="col-sm-2 control-label">
    			<%= f.label :description %>
    		</div>
    		
    		<div class="col-sm-6">
      			<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Article Description"  %>
    		</div>
  		</div>
   

		<div class="form-group">
    		<div class="col-sm-offset-2 col-sm-10">
    			<%= f.submit class:"btn btn-default" %>
    		</div>
  		</div>
  
		<% end %>
		<%= render "shared/footer" %>
	</div>
</div>

app/views/articles/edit.html.erb
<h1>Edit an article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1>Listing all Articles</h1>
<div align="center">
	<%= will_paginate %>
</div>

<%= render "article", objs: @articles %>

<div align="center">
	<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<div class="text-center text-capitalize">
<h2>Title: <%= @article.title %></h2>
</div>
	<div class="col-xs-8 col-xs-offset-2 text-left">
	<% if @article.user %>
	<div class="center">Created By:</div>
		<%= render "users/gravatar", user: @article.user %>
		<% end %>
	<h4 class="center"><strong>Description: </strong></h4>
	<hr>
	<%= simple_format(@article.description) %>

<%= render "shared/footer" %>
<%= render "articleactions" , obj: @article, article_user: @article.user %>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
	<small>
	Copyright &copy; 2016 KW - All rights reserved.
	</small>
	
	<nav>
	<ul>
		<li> <%= link_to "Home", root_path %></li>
		<li><%= link_to "About", pages_about_path %></li>
		</ul>
	</nav>
	
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do | name, msg |  %>
			<div class='alert alert-<%="#{name}" %>'>
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		<% end %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <!-- <a class="navbar-brand" id="logo" href="#">KW's Blog</a> -->
      <%= link_to "KW's Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="#">Articles<span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
          <ul class="dropdown-menu">
           <!-- <li><a href="#">Action</a></li> -->
           <li><%= link_to "Create New Article", new_article_path %>
            <!-- <li><a href="#">Another action</a></li> -->
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right"
      <% if logged_in? %>
         	<li><%= link_to "Logout", logout_path, method: :delete %></li>
       	<li class="dropdown">
         	 <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <span class="caret"></span></a>
         		 <ul class="dropdown-menu">
            		<li><%= link_to "Edit Your Profile", edit_user_path(current_user) %></li>
            		<li><%= link_to "View Your Profile", user_path(current_user) %></li>
            		<li><a href="#">Something else here</a></li>
            		<li role="separator" class="divider"></li>
            		<li><a href="#">Separated link</a></li>
          	</ul>
        	</li>
       <% else %>
           	<li><%= link_to "Login", login_path %></li>
         		<li><%= link_to "Sign Up", signup_path %></li>
       <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KW's Alpha Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar" %>
<%= render "layouts/messages" %>

<div class="container center">
	<%= yield %>
</div>

<%= render "layouts/footer" %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Page!</h1>

<%= render "articles/footer" %>
<%= image_tag 'orange-fractal-spiral.jpg' %>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>KW's Blog Home Page</h1>
  <p><!--<a class="btn btn-primary btn-lg btn-xlg" role="button"><%= link_to "Sign Up!", signup_path %></a-->
  		<%= link_to "Sign Up!", signup_path, class: "btn btn-primary btn-lg btn-xlg", role: "button" %>
  </p>
  

<%= image_tag 'orange-fractal-spiral.jpg' %><br>
 <%= link_to "About", pages_about_path %> | <%= link_to "Articles", articles_path %>
</div>

app/views/shared/_errors.html.erb
<% if (obj.errors.any?) %>
	<div class="row text-left">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
				
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "error") %>
						prohibited this article from being saved:
					</h2>	
					
					<div class="panel-body">
						<ul>
							<%  obj.errors.full_messages.each do |msg| %>
								<li> <%= msg %> </li>
							<% end %>
						</ul>
					</div>		
						
				</div>
			</div>
		</div>	
	</div>
	<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>
	
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@user, :html=>{class:"form-horizontal", role:"form"}) do |f| %>
		<div class="form-group">
    		<div class="col-sm-2 control-label">
    			<%= f.label :username %>
    		</div>
    		
    		<div class="col-sm-6">
      			<%= f.text_field :username, class: "form-control", placeholder: placeholderUsername, autofocus: true  %>
    		</div>
  		</div>
  
   		<div class="form-group">
    		<div class="col-sm-2 control-label">
    			<%= f.label :email %>
    		</div>
    		
    		<div class="col-sm-6">
      			<%= f.email_field :email, class: "form-control", placeholder: placeholderEmail  %>
    		</div>
  		</div>
   
  		<div class="form-group">
    		<div class="col-sm-2 control-label">
    			<%= f.label :password %>
    		</div>
    		
    		<div class="col-sm-6">
      			<%= f.password_field :password, class: "form-control", placeholder: placeholderPasswd  %>
    		</div>
  		</div>
   

		<div class="form-group">
    		<div class="col-sm-offset-2 col-sm-10">
    			<%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class:"btn btn-default") %>
    		</div>
  		</div>
  
		<% end %>
		<%= render "shared/footer" %>
	</div>
</div>

app/views/users/_gravatar.html.erb
	<% if user %>		
		<ul class="listing">
			<div class="row center">
				<div class="well col-md-4 col-md-offset-4">
					<li><%= link_to gravatar_for(user), user_path(user) %></li>
					<li class="article-title"><%= link_to user.username, user_path(user) %></li>
					<li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
				</div>		
			</div>	
		</ul>
	<% end %>		

app/views/users/create.html.erb
<h1>TEST CREATE USER</h1>

app/views/users/edit.html.erb
<h1 align="center">Edit Your Account</h1>
<%= render "form", placeholderUsername: "Update Username", placeholderEmail: "Update Email", placeholderPasswd: "Update Password" %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>

<div align="center">
	<% @users.each do |user| %>
		<%= render "gravatar", user: user %>
	<% end %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign Up for New Account</h1>

<%= render "form", placeholderUsername: "Enter User", placeholderEmail: "Enter Email", placeholderPasswd: "Enter Password" %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s Page!</h1>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>

<h4 align="center">Welcome to <%= @user.username %>'s Articles!</h4>

<% if @user_articles %>
<div align="center">
	<%= will_paginate @user_articles %>
</div>

	<%= render "articles/article", objs: @user_articles %>

<div align="center">
	<%= will_paginate @user_articles %>
</div>

<% end %>